spring:
  datasource:
    url: jdbc:mariadb://testdb.cvsmfe2ldref.ap-northeast-2.rds.amazonaws.com:3306/nextmagic?ssl=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: wisdomguy
    password: qhdks77!#
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect